using LoLRunes.CustumAttributes;

namespace LoLRunes.Enumerators
{
    public enum RuneTypeEnum
    {
        //Precision
        PRECISION_PATH,
        PRECISION_KEYSTONE_01,
        PRECISION_KEYSTONE_02,
        PRECISION_KEYSTONE_03,
        PRECISION_KEYSTONE_04,
        PRECISION_RUNE_SLOT_01,
        PRECISION_RUNE_SLOT_02,
        PRECISION_RUNE_SLOT_03,
        PRECISION_RUNE_SLOT_04,
        PRECISION_RUNE_SLOT_05,
        PRECISION_RUNE_SLOT_06,
        PRECISION_RUNE_SLOT_07,
        PRECISION_RUNE_SLOT_08,
        PRECISION_RUNE_SLOT_09,

        //Domination
        DOMINATION_PATH,
        DOMINATION_KEYSTONE_01,
        DOMINATION_KEYSTONE_02,
        DOMINATION_KEYSTONE_03,
        DOMINATION_KEYSTONE_04,
        DOMINATION_RUNE_SLOT_01,
        DOMINATION_RUNE_SLOT_02,
        DOMINATION_RUNE_SLOT_03,
        DOMINATION_RUNE_SLOT_04,
        DOMINATION_RUNE_SLOT_05,
        DOMINATION_RUNE_SLOT_06,
        DOMINATION_RUNE_SLOT_07,
        DOMINATION_RUNE_SLOT_08,
        DOMINATION_RUNE_SLOT_09,
        DOMINATION_RUNE_SLOT_10,

        //Sorcery
        SORCERY_PATH,
        SORCERY_KEYSTONE_01,
        SORCERY_KEYSTONE_02,
        SORCERY_KEYSTONE_03,
        SORCERY_RUNE_SLOT_01,
        SORCERY_RUNE_SLOT_02,
        SORCERY_RUNE_SLOT_03,
        SORCERY_RUNE_SLOT_04,
        SORCERY_RUNE_SLOT_05,
        SORCERY_RUNE_SLOT_06,
        SORCERY_RUNE_SLOT_07,
        SORCERY_RUNE_SLOT_08,
        SORCERY_RUNE_SLOT_09,

        //Resolve
        RESOLVE_PATH,
        RESOLVE_KEYSTONE_01,
        RESOLVE_KEYSTONE_02,
        RESOLVE_KEYSTONE_03,
        RESOLVE_RUNE_SLOT_01,
        RESOLVE_RUNE_SLOT_02,
        RESOLVE_RUNE_SLOT_03,
        RESOLVE_RUNE_SLOT_04,
        RESOLVE_RUNE_SLOT_05,
        RESOLVE_RUNE_SLOT_06,
        RESOLVE_RUNE_SLOT_07,
        RESOLVE_RUNE_SLOT_08,
        RESOLVE_RUNE_SLOT_09,

        //Inspiration
        INPIRATION_PATH,
        INPIRATION_KEYSTONE_01,
        INPIRATION_KEYSTONE_02,
        INPIRATION_KEYSTONE_03,
        INPIRATION_RUNE_SLOT_01,
        INPIRATION_RUNE_SLOT_02,
        INPIRATION_RUNE_SLOT_03,
        INPIRATION_RUNE_SLOT_04,
        INPIRATION_RUNE_SLOT_05,
        INPIRATION_RUNE_SLOT_06,
        INPIRATION_RUNE_SLOT_07,
        INPIRATION_RUNE_SLOT_08,
        INPIRATION_RUNE_SLOT_09,

        //Rune Shards
        SHARD_SLOT_01,
        SHARD_SLOT_02,
        SHARD_SLOT_03,
        SHARD_SLOT_04,
        SHARD_SLOT_05,
        SHARD_SLOT_06,
        SHARD_SLOT_07,
        SHARD_SLOT_08,
        SHARD_SLOT_09,
    }
}
